name: Spell checking
on:
  workflow_call:
    inputs:
      debug:
        description: 'Debug'
        required: false
        type: boolean
      experimental_path:
        description: 'Directory root to check for spelling (note that bucket/project/config are independent of this)'
        required: false
        type: string
        default: '.'

jobs:
  update:
    name: Update PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: check-spelling
      uses: check-spelling/check-spelling@prerelease
      with:
        debug: ${{ inputs.debug }}
        experimental_apply_changes_via_bot: 1
        experimental_path: ${{ inputs.experimental_path }}
